version: 0.2

env:
  parameter-store:
    Password: "DigiroadUserPassword"
    Username: "DigiroadUserUsername"

phases:
  build:
    commands:
      - echo Selecting browser based on weekday
      - if [ $( date '+%u' ) -le 5 ]; then SELAIN=headlesschrome; else SELAIN=headlessfirefox;  fi
      - echo Selected Browser=$SELAIN
      - xvfb-run --server-args="-screen 0 1920x1080x24 -ac" robot --xunit xunitlog.xml -d /robotlogs -T -v LiviUSER:$Username -v LiviPWD:$Password -v BROWSER:$SELAIN Robot-Tests/

artifacts:
  files:
    - '/robotlogs/*'
  name: $(date +%Y-%m-%d)-$SELAIN