version: 0.2

#env:
#  parameter-store:
#    Password: "DigiroadUserPassword"

phases:
  install:
    commands:
      - pip install --upgrade awscli
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - docker build -f CI/Docker-image/Dockerfile.robot --build-arg image=475079312496.dkr.ecr.eu-west-1.amazonaws.com/python-alpine:latest -t 475079312496.dkr.ecr.eu-west-1.amazonaws.com/digiroadautomation:latest .
      - docker tag 475079312496.dkr.ecr.eu-west-1.amazonaws.com/digiroadautomation:latest 475079312496.dkr.ecr.eu-west-1.amazonaws.com/digiroadautomation:$CODEBUILD_BUILD_NUMBER
      - docker push 475079312496.dkr.ecr.eu-west-1.amazonaws.com/digiroadautomation:latest
      - docker push 475079312496.dkr.ecr.eu-west-1.amazonaws.com/digiroadautomation:$CODEBUILD_BUILD_NUMBER
